apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nvidia-deviceplugin-daemonset
  namespace: nvidia-device-plugin
spec:
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: openshift.com/gpu-accelerator 
                operator: Exists
      serviceAccount: nvidia-deviceplugin
      serviceAccountName: nvidia-deviceplugin
      hostNetwork: true
      hostPID: true
      containers:
      - image: nvidia/k8s-device-plugin:1.11-centos7
        name: nvidia-device-plugin-ctr
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins