---

- name: install kernel-devel
  yum: name=kernel-devel-{{ ansible_kernel }} state=present

- name: install vulkan-filesystem
  yum: name=http://mirror.centos.org/centos/7/os/x86_64/Packages/vulkan-filesystem-1.1.73.0-1.el7.noarch.rpm state=present

- name: install EPEL
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: install NVIDIA repo
  yum: name=https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-repo-rhel7-10.1.105-1.x86_64.rpm state=present

- name: install NVIDIA drivers
  yum:  name={{item}} state=present
  with_items:
   - nvidia-driver
   - nvidia-driver-devel
   - nvidia-driver-cuda
   - nvidia-modprobe

- name: load NVIDIA and unified memory kernel modules
  shell: nvidia-modprobe && nvidia-modprobe -u

- name: test drivers
  shell: nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0
