apiVersion: v1

kind: Pod

metadata:
  name: gpu-pod
  namespace: nvidia

spec:
  restartPolicy: OnFailure
  serviceAccount: nvidia-deviceplugin
  serviceAccountName: nvidia-deviceplugin

  containers:
  - name: nvidia-cuda-91-centos7-devel
    image: jeremyeder/ocp-gpu-pod:latest
    env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "compute,utility"
      - name: NVIDIA_REQUIRE_CUDA
        value: "cuda>=5.0"

    securityContext:
      privileged: true

    command: ["sleep"]
    args: ["infinity"]

    resources:
      limits:
        nvidia.com/gpu: 1

  tolerations:                        
    - key: "nvidia.com/gpu"           
      operator: "Equal"               
      value: "value"                  
      effect: "NoSchedule"
