apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: smoketest
spec:
  restartPolicy: OnFailure
  serviceAccount: smoketest
  serviceAccountName: smoketest
  containers:
  - name: nvidia-cuda-10-1-centos7-devel
    image: quay.io/don7exc/ocp-gpu:latest
    env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "compute,utility"
      - name: NVIDIA_REQUIRE_CUDA
        value: "cuda>=9.0"
    securityContext:
      privileged: true
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
  tolerations:                        
    - key: "nvidia.com/gpu"           
      operator: "Equal"               
      value: "value"                  
      effect: "NoSchedule"
